//! The idempotent bulk-write algorithm: one `tokio_postgres` transaction per [`ReplayBatch`].
//!
//! Shape (see the task brief for the full rationale):
//! 1. `BEGIN` (via `client.transaction()`).
//! 2. Create four `TEMP … ON COMMIT DROP` staging tables with plain column types (enum columns
//!    as `TEXT`; no `elo_bucket` column on the players staging — it is generated by the DB).
//! 3. Binary `COPY IN` each `Vec<DTO>` into its staging table.
//! 4. Insert matches, capturing only genuinely-new ids in a `new_match_ids` TEMP table, then gate
//!    every child insert on a `JOIN … USING (match_id)` against it — re-ingesting an
//!    already-seen batch inserts zero rows anywhere.
//! 5. `COMMIT` and return the row counts.
//!
//! A DB error at any step (e.g. a FK violation on `map_id`/`civ_id`) propagates as `Err` and the
//! transaction rolls back on drop — nothing partial is ever committed.

use anyhow::{Context, Result};
use tokio_postgres::binary_copy::BinaryCopyInWriter;
use tokio_postgres::types::{ToSql, Type};
use tokio_postgres::{Client, Transaction};

use crate::dto::{
    IngestStats, NewMatch, NewMatchPlayer, NewReplayAge, NewReplayEvent, ReplayBatch,
};

const CREATE_STAGING_TABLES_SQL: &str = r#"
CREATE TEMP TABLE stg_matches (
    match_id BIGINT NOT NULL,
    source TEXT NOT NULL,
    ladder TEXT NOT NULL,
    map_id INTEGER NOT NULL,
    build INTEGER,
    patch TEXT,
    played_at TIMESTAMPTZ NOT NULL,
    duration_ms INTEGER,
    n_players SMALLINT NOT NULL
) ON COMMIT DROP;

CREATE TEMP TABLE stg_match_players (
    match_id BIGINT NOT NULL,
    profile_id BIGINT NOT NULL,
    civ_id INTEGER NOT NULL,
    elo INTEGER,
    won BOOLEAN,
    opening TEXT,
    feudal_t DOUBLE PRECISION,
    castle_t DOUBLE PRECISION,
    imperial_t DOUBLE PRECISION
) ON COMMIT DROP;

CREATE TEMP TABLE stg_replay_events (
    match_id BIGINT NOT NULL,
    profile_id BIGINT,
    player_number SMALLINT NOT NULL,
    t_ms INTEGER NOT NULL,
    kind TEXT NOT NULL,
    target_id BIGINT,
    amount BIGINT,
    detail TEXT
) ON COMMIT DROP;

CREATE TEMP TABLE stg_replay_ages (
    match_id BIGINT NOT NULL,
    profile_id BIGINT NOT NULL,
    civ_id INTEGER NOT NULL,
    won BOOLEAN,
    age TEXT NOT NULL,
    uptime_ms INTEGER NOT NULL,
    villagers INTEGER,
    military INTEGER,
    n_buildings INTEGER,
    n_research INTEGER
) ON COMMIT DROP;
"#;

const COPY_MATCHES_SQL: &str = "COPY stg_matches \
    (match_id, source, ladder, map_id, build, patch, played_at, duration_ms, n_players) \
    FROM STDIN BINARY";
const COPY_MATCH_PLAYERS_SQL: &str = "COPY stg_match_players \
    (match_id, profile_id, civ_id, elo, won, opening, feudal_t, castle_t, imperial_t) \
    FROM STDIN BINARY";
const COPY_REPLAY_EVENTS_SQL: &str = "COPY stg_replay_events \
    (match_id, profile_id, player_number, t_ms, kind, target_id, amount, detail) \
    FROM STDIN BINARY";
const COPY_REPLAY_AGES_SQL: &str = "COPY stg_replay_ages \
    (match_id, profile_id, civ_id, won, age, uptime_ms, villagers, military, n_buildings, n_research) \
    FROM STDIN BINARY";

/// Insert genuinely-new matches (by `match_id`) and capture their ids in a TEMP table so the
/// three child inserts below can gate on it. `source`/`ladder` are cast from the staging table's
/// plain `TEXT` to the real `source_kind`/`ladder_kind` enums here — the only place a cast is
/// needed, since every other column is already a plain type on both sides.
const INSERT_NEW_MATCHES_SQL: &str = r#"
CREATE TEMP TABLE new_match_ids ON COMMIT DROP AS
  WITH ins AS (
    INSERT INTO matches (match_id, source, ladder, map_id, build, patch, played_at, duration_ms, n_players)
    SELECT match_id, source::source_kind, ladder::ladder_kind, map_id, build, patch, played_at, duration_ms, n_players
    FROM stg_matches
    ON CONFLICT (match_id) DO NOTHING
    RETURNING match_id
  )
  SELECT match_id FROM ins
"#;

const INSERT_MATCH_PLAYERS_SQL: &str = r#"
INSERT INTO match_players (match_id, profile_id, civ_id, elo, won, opening, feudal_t, castle_t, imperial_t)
  SELECT s.match_id, s.profile_id, s.civ_id, s.elo, s.won, s.opening, s.feudal_t, s.castle_t, s.imperial_t
  FROM stg_match_players s JOIN new_match_ids n USING (match_id)
"#;

const INSERT_REPLAY_EVENTS_SQL: &str = r#"
INSERT INTO replay_events (match_id, profile_id, player_number, t_ms, kind, target_id, amount, detail)
  SELECT s.match_id, s.profile_id, s.player_number, s.t_ms, s.kind, s.target_id, s.amount, s.detail
  FROM stg_replay_events s JOIN new_match_ids n USING (match_id)
"#;

const INSERT_REPLAY_AGES_SQL: &str = r#"
INSERT INTO replay_ages (match_id, profile_id, civ_id, won, age, uptime_ms, villagers, military, n_buildings, n_research)
  SELECT s.match_id, s.profile_id, s.civ_id, s.won, s.age, s.uptime_ms, s.villagers, s.military, s.n_buildings, s.n_research
  FROM stg_replay_ages s JOIN new_match_ids n USING (match_id)
"#;

/// Idempotently bulk-load a [`ReplayBatch`] into the live schema (see the module docs for the
/// exact algorithm). Re-ingesting an identical batch leaves every table's row count unchanged.
///
/// Never fabricates a missing required field — the DTOs make `map_id`/`played_at`/`ladder`/
/// `source`/`civ_id` non-optional, so a caller without a real value fails to compile. A FK
/// violation (unknown `map_id`/`civ_id`) or any other DB error surfaces as `Err`; the transaction
/// then rolls back on drop (nothing partial is ever committed).
pub async fn ingest_batch(client: &mut Client, batch: &ReplayBatch) -> Result<IngestStats> {
    let tx = client
        .transaction()
        .await
        .context("failed to begin ingest transaction")?;

    tx.batch_execute(CREATE_STAGING_TABLES_SQL)
        .await
        .context("failed to create staging tables")?;

    copy_matches(&tx, &batch.matches).await?;
    copy_match_players(&tx, &batch.players).await?;
    copy_replay_events(&tx, &batch.events).await?;
    copy_replay_ages(&tx, &batch.ages).await?;

    let matches_inserted = tx
        .execute(INSERT_NEW_MATCHES_SQL, &[])
        .await
        .context("failed to insert new matches")?;
    let matches_skipped = (batch.matches.len() as u64).saturating_sub(matches_inserted);

    let players = tx
        .execute(INSERT_MATCH_PLAYERS_SQL, &[])
        .await
        .context("failed to insert match_players")?;
    let events = tx
        .execute(INSERT_REPLAY_EVENTS_SQL, &[])
        .await
        .context("failed to insert replay_events")?;
    let ages = tx
        .execute(INSERT_REPLAY_AGES_SQL, &[])
        .await
        .context("failed to insert replay_ages")?;

    tx.commit()
        .await
        .context("failed to commit ingest transaction")?;

    let stats = IngestStats {
        matches_inserted,
        matches_skipped,
        players,
        events,
        ages,
    };
    tracing::info!(?stats, "ingest batch committed");
    Ok(stats)
}

async fn copy_matches(tx: &Transaction<'_>, rows: &[NewMatch]) -> Result<()> {
    let sink = tx
        .copy_in(COPY_MATCHES_SQL)
        .await
        .context("failed to start COPY IN for stg_matches")?;
    let types = [
        Type::INT8,
        Type::TEXT,
        Type::TEXT,
        Type::INT4,
        Type::INT4,
        Type::TEXT,
        Type::TIMESTAMPTZ,
        Type::INT4,
        Type::INT2,
    ];
    let writer = BinaryCopyInWriter::new(sink, &types);
    tokio::pin!(writer);
    for row in rows {
        let source = row.source.as_db_str();
        let ladder = row.ladder.as_db_str();
        let params: [&(dyn ToSql + Sync); 9] = [
            &row.match_id,
            &source,
            &ladder,
            &row.map_id,
            &row.build,
            &row.patch,
            &row.played_at,
            &row.duration_ms,
            &row.n_players,
        ];
        writer
            .as_mut()
            .write(&params)
            .await
            .context("COPY IN write failed for stg_matches")?;
    }
    writer
        .as_mut()
        .finish()
        .await
        .context("COPY IN finish failed for stg_matches")?;
    Ok(())
}

async fn copy_match_players(tx: &Transaction<'_>, rows: &[NewMatchPlayer]) -> Result<()> {
    let sink = tx
        .copy_in(COPY_MATCH_PLAYERS_SQL)
        .await
        .context("failed to start COPY IN for stg_match_players")?;
    let types = [
        Type::INT8,
        Type::INT8,
        Type::INT4,
        Type::INT4,
        Type::BOOL,
        Type::TEXT,
        Type::FLOAT8,
        Type::FLOAT8,
        Type::FLOAT8,
    ];
    let writer = BinaryCopyInWriter::new(sink, &types);
    tokio::pin!(writer);
    for row in rows {
        let params: [&(dyn ToSql + Sync); 9] = [
            &row.match_id,
            &row.profile_id,
            &row.civ_id,
            &row.elo,
            &row.won,
            &row.opening,
            &row.feudal_t,
            &row.castle_t,
            &row.imperial_t,
        ];
        writer
            .as_mut()
            .write(&params)
            .await
            .context("COPY IN write failed for stg_match_players")?;
    }
    writer
        .as_mut()
        .finish()
        .await
        .context("COPY IN finish failed for stg_match_players")?;
    Ok(())
}

async fn copy_replay_events(tx: &Transaction<'_>, rows: &[NewReplayEvent]) -> Result<()> {
    let sink = tx
        .copy_in(COPY_REPLAY_EVENTS_SQL)
        .await
        .context("failed to start COPY IN for stg_replay_events")?;
    let types = [
        Type::INT8,
        Type::INT8,
        Type::INT2,
        Type::INT4,
        Type::TEXT,
        Type::INT8,
        Type::INT8,
        Type::TEXT,
    ];
    let writer = BinaryCopyInWriter::new(sink, &types);
    tokio::pin!(writer);
    for row in rows {
        let params: [&(dyn ToSql + Sync); 8] = [
            &row.match_id,
            &row.profile_id,
            &row.player_number,
            &row.t_ms,
            &row.kind,
            &row.target_id,
            &row.amount,
            &row.detail,
        ];
        writer
            .as_mut()
            .write(&params)
            .await
            .context("COPY IN write failed for stg_replay_events")?;
    }
    writer
        .as_mut()
        .finish()
        .await
        .context("COPY IN finish failed for stg_replay_events")?;
    Ok(())
}

async fn copy_replay_ages(tx: &Transaction<'_>, rows: &[NewReplayAge]) -> Result<()> {
    let sink = tx
        .copy_in(COPY_REPLAY_AGES_SQL)
        .await
        .context("failed to start COPY IN for stg_replay_ages")?;
    let types = [
        Type::INT8,
        Type::INT8,
        Type::INT4,
        Type::BOOL,
        Type::TEXT,
        Type::INT4,
        Type::INT4,
        Type::INT4,
        Type::INT4,
        Type::INT4,
    ];
    let writer = BinaryCopyInWriter::new(sink, &types);
    tokio::pin!(writer);
    for row in rows {
        let params: [&(dyn ToSql + Sync); 10] = [
            &row.match_id,
            &row.profile_id,
            &row.civ_id,
            &row.won,
            &row.age,
            &row.uptime_ms,
            &row.villagers,
            &row.military,
            &row.n_buildings,
            &row.n_research,
        ];
        writer
            .as_mut()
            .write(&params)
            .await
            .context("COPY IN write failed for stg_replay_ages")?;
    }
    writer
        .as_mut()
        .finish()
        .await
        .context("COPY IN finish failed for stg_replay_ages")?;
    Ok(())
}
