//! The idempotent bulk-write algorithm: one `tokio_postgres` transaction per [`ReplayBatch`].
//!
//! Shape (see the task brief for the full rationale):
//! 1. `BEGIN` (via `client.transaction()`).
//! 2. Create six `TEMP … ON COMMIT DROP` staging tables with plain column types (enum/`Age`
//!    columns as `TEXT`; no `elo_bucket` column on the players staging — it is generated by the
//!    DB).
//! 3. Binary `COPY IN` each `Vec<DTO>` into its staging table.
//! 4. Insert matches, capturing only genuinely-new ids in a `new_match_ids` TEMP table, then gate
//!    every child insert on a `JOIN … USING (match_id)` against it — re-ingesting an
//!    already-seen batch inserts zero rows anywhere.
//! 5. `COMMIT` and return the row counts.
//!
//! A DB error at any step (e.g. a FK violation on `map_id`/`civ_id`) propagates as `Err` and the
//! transaction rolls back on drop — nothing partial is ever committed.

use anyhow::{Context, Result};
use tokio_postgres::binary_copy::BinaryCopyInWriter;
use tokio_postgres::types::{ToSql, Type};
use tokio_postgres::{Client, Transaction};

use crate::dto::{
    IngestStats, NewMatch, NewMatchPlayer, NewMatchPlayerTech, NewMatchPlayerUnit, NewReplayAge,
    NewReplayEvent, ReplayBatch,
};

/// One staging table's COPY column list: `(column name, wire type)` pairs in the exact COPY
/// order. Declaring this ONCE per table — instead of hand-syncing the `COPY` SQL string, the
/// `[Type; N]` array, and the per-row `[&dyn ToSql; N]` params independently — means the SQL
/// column list and the `Type` list can never drift apart. The per-row params array below still
/// has to be written in the same order by hand (there is no reflection from a `(&str, Type)` pair
/// to "the struct field with that name"), so it remains the one place a future column addition
/// must also touch — but that is now a 2-way, not 3-way, sync.
struct TableColumns {
    staging_table: &'static str,
    columns: &'static [(&'static str, Type)],
}

impl TableColumns {
    /// `COPY <staging_table> (<col, col, ...>) FROM STDIN BINARY`, built from `columns` so the
    /// column list is always in the same order as [`Self::types`].
    fn copy_sql(&self) -> String {
        let names: Vec<&str> = self.columns.iter().map(|(name, _)| *name).collect();
        format!(
            "COPY {} ({}) FROM STDIN BINARY",
            self.staging_table,
            names.join(", ")
        )
    }

    /// The wire `Type` list, in the same order as [`Self::copy_sql`]'s column list.
    fn types(&self) -> Vec<Type> {
        self.columns.iter().map(|(_, ty)| ty.clone()).collect()
    }
}

const MATCHES_COLUMNS: TableColumns = TableColumns {
    staging_table: "stg_matches",
    columns: &[
        ("match_id", Type::INT8),
        ("source", Type::TEXT),
        ("ladder", Type::TEXT),
        ("map_id", Type::INT4),
        ("build", Type::INT4),
        ("patch", Type::TEXT),
        ("played_at", Type::TIMESTAMPTZ),
        ("duration_ms", Type::INT4),
        ("n_players", Type::INT2),
    ],
};

const MATCH_PLAYERS_COLUMNS: TableColumns = TableColumns {
    staging_table: "stg_match_players",
    columns: &[
        ("match_id", Type::INT8),
        ("profile_id", Type::INT8),
        ("civ_id", Type::INT4),
        ("elo", Type::INT4),
        ("won", Type::BOOL),
        ("opening", Type::TEXT),
        // `real`/float4 in Postgres (`m20260705_000007_create_match_players.rs`) — FLOAT4, not
        // FLOAT8, so the wire type matches the column exactly. See `dto::NewMatchPlayer`.
        ("feudal_t", Type::FLOAT4),
        ("castle_t", Type::FLOAT4),
        ("imperial_t", Type::FLOAT4),
        // `real`/float4 (`m20260706_000013_add_match_players_apm.rs`) — same treatment as
        // `feudal_t`/`castle_t`/`imperial_t` above.
        ("apm", Type::FLOAT4),
    ],
};

const REPLAY_EVENTS_COLUMNS: TableColumns = TableColumns {
    staging_table: "stg_replay_events",
    columns: &[
        ("match_id", Type::INT8),
        ("profile_id", Type::INT8),
        ("player_number", Type::INT2),
        ("t_ms", Type::INT4),
        ("kind", Type::TEXT),
        ("target_id", Type::INT8),
        ("amount", Type::INT8),
        ("detail", Type::TEXT),
    ],
};

const REPLAY_AGES_COLUMNS: TableColumns = TableColumns {
    staging_table: "stg_replay_ages",
    columns: &[
        ("match_id", Type::INT8),
        ("profile_id", Type::INT8),
        ("civ_id", Type::INT4),
        ("won", Type::BOOL),
        ("age", Type::TEXT),
        ("uptime_ms", Type::INT4),
        ("villagers", Type::INT4),
        ("military", Type::INT4),
        ("n_buildings", Type::INT4),
        ("n_research", Type::INT4),
    ],
};

const MATCH_PLAYER_UNITS_COLUMNS: TableColumns = TableColumns {
    staging_table: "stg_match_player_units",
    columns: &[
        ("match_id", Type::INT8),
        ("profile_id", Type::INT8),
        ("unit_id", Type::INT4),
        ("trained", Type::INT4),
    ],
};

const MATCH_PLAYER_TECHS_COLUMNS: TableColumns = TableColumns {
    staging_table: "stg_match_player_techs",
    columns: &[
        ("match_id", Type::INT8),
        ("profile_id", Type::INT8),
        ("tech_id", Type::INT4),
        ("t_ms", Type::INT4),
    ],
};

const CREATE_STAGING_TABLES_SQL: &str = r#"
CREATE TEMP TABLE stg_matches (
    match_id BIGINT NOT NULL,
    source TEXT NOT NULL,
    ladder TEXT NOT NULL,
    map_id INTEGER NOT NULL,
    build INTEGER,
    patch TEXT,
    played_at TIMESTAMPTZ NOT NULL,
    duration_ms INTEGER,
    n_players SMALLINT NOT NULL
) ON COMMIT DROP;

CREATE TEMP TABLE stg_match_players (
    match_id BIGINT NOT NULL,
    profile_id BIGINT NOT NULL,
    civ_id INTEGER NOT NULL,
    elo INTEGER,
    won BOOLEAN,
    opening TEXT,
    feudal_t REAL,
    castle_t REAL,
    imperial_t REAL,
    apm REAL
) ON COMMIT DROP;

CREATE TEMP TABLE stg_replay_events (
    match_id BIGINT NOT NULL,
    profile_id BIGINT,
    player_number SMALLINT NOT NULL,
    t_ms INTEGER NOT NULL,
    kind TEXT NOT NULL,
    target_id BIGINT,
    amount BIGINT,
    detail TEXT
) ON COMMIT DROP;

CREATE TEMP TABLE stg_replay_ages (
    match_id BIGINT NOT NULL,
    profile_id BIGINT NOT NULL,
    civ_id INTEGER NOT NULL,
    won BOOLEAN,
    age TEXT NOT NULL,
    uptime_ms INTEGER NOT NULL,
    villagers INTEGER,
    military INTEGER,
    n_buildings INTEGER,
    n_research INTEGER
) ON COMMIT DROP;

CREATE TEMP TABLE stg_match_player_units (
    match_id BIGINT NOT NULL,
    profile_id BIGINT NOT NULL,
    unit_id INTEGER NOT NULL,
    trained INTEGER NOT NULL
) ON COMMIT DROP;

CREATE TEMP TABLE stg_match_player_techs (
    match_id BIGINT NOT NULL,
    profile_id BIGINT NOT NULL,
    tech_id INTEGER NOT NULL,
    t_ms INTEGER NOT NULL
) ON COMMIT DROP;
"#;

/// Insert genuinely-new matches (by `match_id`) and capture their ids in a TEMP table so the
/// three child inserts below can gate on it. `source`/`ladder` are cast from the staging table's
/// plain `TEXT` to the real `source_kind`/`ladder_kind` enums here — one of two places a cast is
/// needed in this function (the other is [`INSERT_REPLAY_AGES_SQL`]'s `age::age_kind`), since
/// every other column is already a plain type on both sides.
const INSERT_NEW_MATCHES_SQL: &str = r#"
CREATE TEMP TABLE new_match_ids ON COMMIT DROP AS
  WITH ins AS (
    INSERT INTO matches (match_id, source, ladder, map_id, build, patch, played_at, duration_ms, n_players)
    SELECT match_id, source::source_kind, ladder::ladder_kind, map_id, build, patch, played_at, duration_ms, n_players
    FROM stg_matches
    ON CONFLICT (match_id) DO NOTHING
    RETURNING match_id
  )
  SELECT match_id FROM ins
"#;

// Children are inserted ONLY for genuinely-new `match_id`s (the `JOIN new_match_ids` below), so
// re-ingesting an already-present match does NOT append new child rows to it — a re-parse that
// discovered additional events (e.g. a fuller replay) will not top up an existing match's rows.
// This is the intended no-churn contract; future producers (Task-4/5) must not rely on
// re-ingestion to backfill/augment children of matches already in the store.
const INSERT_MATCH_PLAYERS_SQL: &str = r#"
INSERT INTO match_players (match_id, profile_id, civ_id, elo, won, opening, feudal_t, castle_t, imperial_t, apm)
  SELECT s.match_id, s.profile_id, s.civ_id, s.elo, s.won, s.opening, s.feudal_t, s.castle_t, s.imperial_t, s.apm
  FROM stg_match_players s JOIN new_match_ids n USING (match_id)
"#;

const INSERT_REPLAY_EVENTS_SQL: &str = r#"
INSERT INTO replay_events (match_id, profile_id, player_number, t_ms, kind, target_id, amount, detail)
  SELECT s.match_id, s.profile_id, s.player_number, s.t_ms, s.kind, s.target_id, s.amount, s.detail
  FROM stg_replay_events s JOIN new_match_ids n USING (match_id)
"#;

/// `age` is cast from the staging table's plain `TEXT` to the `age_kind` enum here — see
/// [`INSERT_NEW_MATCHES_SQL`]'s doc for the other cast this function needs.
const INSERT_REPLAY_AGES_SQL: &str = r#"
INSERT INTO replay_ages (match_id, profile_id, civ_id, won, age, uptime_ms, villagers, military, n_buildings, n_research)
  SELECT s.match_id, s.profile_id, s.civ_id, s.won, s.age::age_kind, s.uptime_ms, s.villagers, s.military, s.n_buildings, s.n_research
  FROM stg_replay_ages s JOIN new_match_ids n USING (match_id)
"#;

/// `unit_id` is a plain `INTEGER` on both sides — no enum cast needed (unlike
/// [`INSERT_REPLAY_AGES_SQL`]'s `age::age_kind`), since `match_player_units` has no dimension
/// table backing it (see the migration's doc for why).
const INSERT_MATCH_PLAYER_UNITS_SQL: &str = r#"
INSERT INTO match_player_units (match_id, profile_id, unit_id, trained)
  SELECT s.match_id, s.profile_id, s.unit_id, s.trained
  FROM stg_match_player_units s JOIN new_match_ids n USING (match_id)
"#;

/// `tech_id` is a plain `INTEGER` on both sides — no enum cast needed, same reasoning as
/// [`INSERT_MATCH_PLAYER_UNITS_SQL`] (`match_player_techs` has no dimension table backing it
/// either; see the migration's doc).
const INSERT_MATCH_PLAYER_TECHS_SQL: &str = r#"
INSERT INTO match_player_techs (match_id, profile_id, tech_id, t_ms)
  SELECT s.match_id, s.profile_id, s.tech_id, s.t_ms
  FROM stg_match_player_techs s JOIN new_match_ids n USING (match_id)
"#;

/// Idempotently bulk-load a [`ReplayBatch`] into the live schema (see the module docs for the
/// exact algorithm). Re-ingesting an identical batch leaves every table's row count unchanged.
///
/// Never fabricates a missing required field — the DTOs make `map_id`/`played_at`/`ladder`/
/// `source`/`civ_id` non-optional, so a caller without a real value fails to compile. A FK
/// violation (unknown `map_id`/`civ_id`) or any other DB error surfaces as `Err`; the transaction
/// then rolls back on drop (nothing partial is ever committed).
pub async fn ingest_batch(client: &mut Client, batch: &ReplayBatch) -> Result<IngestStats> {
    let tx = client
        .transaction()
        .await
        .context("failed to begin ingest transaction")?;

    tx.batch_execute(CREATE_STAGING_TABLES_SQL)
        .await
        .context("failed to create staging tables")?;

    copy_matches(&tx, &batch.matches).await?;
    copy_match_players(&tx, &batch.players).await?;
    copy_replay_events(&tx, &batch.events).await?;
    copy_replay_ages(&tx, &batch.ages).await?;
    copy_match_player_units(&tx, &batch.player_units).await?;
    copy_match_player_techs(&tx, &batch.player_techs).await?;

    let matches_inserted = tx
        .execute(INSERT_NEW_MATCHES_SQL, &[])
        .await
        .context("failed to insert new matches")?;
    let matches_skipped = (batch.matches.len() as u64).saturating_sub(matches_inserted);

    let players = tx
        .execute(INSERT_MATCH_PLAYERS_SQL, &[])
        .await
        .context("failed to insert match_players")?;
    let events = tx
        .execute(INSERT_REPLAY_EVENTS_SQL, &[])
        .await
        .context("failed to insert replay_events")?;
    let ages = tx
        .execute(INSERT_REPLAY_AGES_SQL, &[])
        .await
        .context("failed to insert replay_ages")?;
    let units = tx
        .execute(INSERT_MATCH_PLAYER_UNITS_SQL, &[])
        .await
        .context("failed to insert match_player_units")?;
    let techs = tx
        .execute(INSERT_MATCH_PLAYER_TECHS_SQL, &[])
        .await
        .context("failed to insert match_player_techs")?;

    tx.commit()
        .await
        .context("failed to commit ingest transaction")?;

    let stats = IngestStats {
        matches_inserted,
        matches_skipped,
        players,
        events,
        ages,
        units,
        techs,
    };
    tracing::info!(?stats, "ingest batch committed");
    Ok(stats)
}

async fn copy_matches(tx: &Transaction<'_>, rows: &[NewMatch]) -> Result<()> {
    let sink = tx
        .copy_in(&MATCHES_COLUMNS.copy_sql())
        .await
        .context("failed to start COPY IN for stg_matches")?;
    let types = MATCHES_COLUMNS.types();
    let writer = BinaryCopyInWriter::new(sink, &types);
    tokio::pin!(writer);
    for row in rows {
        let source = row.source.as_db_str();
        let ladder = row.ladder.as_db_str();
        let params: [&(dyn ToSql + Sync); 9] = [
            &row.match_id.0,
            &source,
            &ladder,
            &row.map_id,
            &row.build,
            &row.patch,
            &row.played_at,
            &row.duration_ms,
            &row.n_players,
        ];
        writer
            .as_mut()
            .write(&params)
            .await
            .context("COPY IN write failed for stg_matches")?;
    }
    writer
        .as_mut()
        .finish()
        .await
        .context("COPY IN finish failed for stg_matches")?;
    Ok(())
}

async fn copy_match_players(tx: &Transaction<'_>, rows: &[NewMatchPlayer]) -> Result<()> {
    let sink = tx
        .copy_in(&MATCH_PLAYERS_COLUMNS.copy_sql())
        .await
        .context("failed to start COPY IN for stg_match_players")?;
    let types = MATCH_PLAYERS_COLUMNS.types();
    let writer = BinaryCopyInWriter::new(sink, &types);
    tokio::pin!(writer);
    for row in rows {
        let params: [&(dyn ToSql + Sync); 10] = [
            &row.match_id.0,
            &row.profile_id.0,
            &row.civ_id.0,
            &row.elo,
            &row.won,
            &row.opening,
            &row.feudal_t,
            &row.castle_t,
            &row.imperial_t,
            &row.apm,
        ];
        writer
            .as_mut()
            .write(&params)
            .await
            .context("COPY IN write failed for stg_match_players")?;
    }
    writer
        .as_mut()
        .finish()
        .await
        .context("COPY IN finish failed for stg_match_players")?;
    Ok(())
}

async fn copy_replay_events(tx: &Transaction<'_>, rows: &[NewReplayEvent]) -> Result<()> {
    let sink = tx
        .copy_in(&REPLAY_EVENTS_COLUMNS.copy_sql())
        .await
        .context("failed to start COPY IN for stg_replay_events")?;
    let types = REPLAY_EVENTS_COLUMNS.types();
    let writer = BinaryCopyInWriter::new(sink, &types);
    tokio::pin!(writer);
    for row in rows {
        let profile_id = row.profile_id.map(|id| id.0);
        let params: [&(dyn ToSql + Sync); 8] = [
            &row.match_id.0,
            &profile_id,
            &row.player_number,
            &row.t_ms,
            &row.kind,
            &row.target_id,
            &row.amount,
            &row.detail,
        ];
        writer
            .as_mut()
            .write(&params)
            .await
            .context("COPY IN write failed for stg_replay_events")?;
    }
    writer
        .as_mut()
        .finish()
        .await
        .context("COPY IN finish failed for stg_replay_events")?;
    Ok(())
}

async fn copy_replay_ages(tx: &Transaction<'_>, rows: &[NewReplayAge]) -> Result<()> {
    let sink = tx
        .copy_in(&REPLAY_AGES_COLUMNS.copy_sql())
        .await
        .context("failed to start COPY IN for stg_replay_ages")?;
    let types = REPLAY_AGES_COLUMNS.types();
    let writer = BinaryCopyInWriter::new(sink, &types);
    tokio::pin!(writer);
    for row in rows {
        let age = row.age.as_db_str();
        let params: [&(dyn ToSql + Sync); 10] = [
            &row.match_id.0,
            &row.profile_id.0,
            &row.civ_id.0,
            &row.won,
            &age,
            &row.uptime_ms,
            &row.villagers,
            &row.military,
            &row.n_buildings,
            &row.n_research,
        ];
        writer
            .as_mut()
            .write(&params)
            .await
            .context("COPY IN write failed for stg_replay_ages")?;
    }
    writer
        .as_mut()
        .finish()
        .await
        .context("COPY IN finish failed for stg_replay_ages")?;
    Ok(())
}

async fn copy_match_player_units(tx: &Transaction<'_>, rows: &[NewMatchPlayerUnit]) -> Result<()> {
    let sink = tx
        .copy_in(&MATCH_PLAYER_UNITS_COLUMNS.copy_sql())
        .await
        .context("failed to start COPY IN for stg_match_player_units")?;
    let types = MATCH_PLAYER_UNITS_COLUMNS.types();
    let writer = BinaryCopyInWriter::new(sink, &types);
    tokio::pin!(writer);
    for row in rows {
        let params: [&(dyn ToSql + Sync); 4] = [
            &row.match_id.0,
            &row.profile_id.0,
            &row.unit_id.0,
            &row.trained,
        ];
        writer
            .as_mut()
            .write(&params)
            .await
            .context("COPY IN write failed for stg_match_player_units")?;
    }
    writer
        .as_mut()
        .finish()
        .await
        .context("COPY IN finish failed for stg_match_player_units")?;
    Ok(())
}

async fn copy_match_player_techs(tx: &Transaction<'_>, rows: &[NewMatchPlayerTech]) -> Result<()> {
    let sink = tx
        .copy_in(&MATCH_PLAYER_TECHS_COLUMNS.copy_sql())
        .await
        .context("failed to start COPY IN for stg_match_player_techs")?;
    let types = MATCH_PLAYER_TECHS_COLUMNS.types();
    let writer = BinaryCopyInWriter::new(sink, &types);
    tokio::pin!(writer);
    for row in rows {
        let params: [&(dyn ToSql + Sync); 4] =
            [&row.match_id.0, &row.profile_id.0, &row.tech_id.0, &row.t_ms];
        writer
            .as_mut()
            .write(&params)
            .await
            .context("COPY IN write failed for stg_match_player_techs")?;
    }
    writer
        .as_mut()
        .finish()
        .await
        .context("COPY IN finish failed for stg_match_player_techs")?;
    Ok(())
}
